# Generated by Django 4.2.10 on 2024-03-12 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='expired_date',
            field=models.DateTimeField(),
        ),
    ]
