# Generated by Django 4.2.10 on 2024-03-12 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0002_alter_card_expired_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='expired_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
