# Generated by Django 4.2.10 on 2024-03-14 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0003_alter_card_expired_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='money',
            field=models.FloatField(default=0),
        ),
    ]
