# Generated by Django 4.2.10 on 2024-03-14 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0005_payhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='payhistory',
            name='type_money',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
