# Generated by Django 4.2.10 on 2024-03-12 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foydalanuvchilar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ismi', models.CharField(max_length=32)),
                ('familyasi', models.CharField(max_length=32)),
                ('parol', models.CharField(max_length=64)),
                ('telefon_raqam', models.IntegerField()),
            ],
        ),
    ]
